name: Build and publish

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [ test ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.SCOPICS_ACESS_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Docker build
        run: docker build -f Dockerfile . -t docker.pkg.github.com/scopics/scode/scode:1.2
      - name: Docker push    
        run: docker push docker.pkg.github.com/scopics/scode/scode:1.2
      - name: View docker images
        run: docker images -a
        
