name: Build and publish

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: docker.pkg.github.com/scopics/scode/scode
  VERSION: latest

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [test]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.SCOPICS_ACESS_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Docker build & push
        run: |
          docker build -f Dockerfile . -t $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
